org.eclipse.sprotty.server/src/main/java/org/eclipse/sprotty/server/json/ActionTypeAdapter.java, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/Actions.xtend, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/DefaultDiagramServer.java, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/ServerLayoutKind.java
=> [layout] introduced manual layout

gradle/versions.gradle
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
=> Updated to Xtext `2.18-SNAPSHOT`.

org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/launch/DiagramLanguageServerSetup.xtend, org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/launch/DiagramServerLauncher.xtend, org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/launch/DiagramServerSocketLauncher.xtend
Closes #13.
Signed-off-by: Akos Kitta <kittaakos@typefox.io>
=> GH-13: Made the language client class configurable in the launchers.

org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/ls/DiagramUpdater.xtend
For better extensibility of the DiagramUpdater, the languageServer field is now protected.
Signed-off-by: Niklas Rentz <nre@informatik.uni-kiel.de>
=> [xtext.ls] Made the languageServer in the DiagramUpdater protected.

org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/DefaultDiagramModule.xtend, org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/ls/DiagramServerModule.xtend
=> [server] bind IDiagramManager in correct LS module

org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/DefaultDiagramServer.java, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/IDiagramServer.java, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/SModelCloner.xtend
=> [layout] manual layout should increment revision number

org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/SModel.xtend
Fix #25 - Add missing properties to LayoutOptions
Signed-off-by: Tobias Ortmayr <tortmayr@eclipsesource.com>
=> Fix #25 - Add missing properties to LayoutOptions

org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/SModel.xtend
Fixes eclipse/sprotty-server#27
=> [docs] fixed wrong JavaDoc

org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/LanguageAwareDiagramServer.xtend
=> [generator] report failed diagram generation as status message

examples/circlegraph/src/main/ts/di.config.ts
=> [layout] make client request server layout

org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/ComputedBoundsApplicator.java
=> [layout] warn on potential client/server version mismatches

org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/SModel.xtend, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/SModelExtensions.xtend
=> [smodel] add more enums

org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/DefaultDiagramServer.java
This is a follow-up of #41. Since the client now determines whether to perform client / server layout, we can read those settings directly from the options.
=> Read client / server layout settings dynamically

org.eclipse.sprotty/.settings/org.eclipse.xtend.core.Xtend.prefs, org.eclipse.sprotty/build.gradle, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/DefaultDiagramServer.java, org.eclipse.sprotty/src/test/java/org/eclipse/sprotty/DefaultDiagramServerTest.xtend, org.eclipse.sprotty/src/test/java/org/eclipse/sprotty/util/TestLogger.xtend, org.eclipse.sprotty/src/test/java/org/eclipse/sprotty/util/TestSetup.xtend
Fixes #53. Added tests for DefaultDiagramServer.
=> Log exceptions that occur while processing ComputedBoundsAction

build.gradle, gradle/manifest-gen.gradle, gradle/versions.gradle
=> OSGi compliant jars

org.eclipse.sprotty.layout/src/test/java/org/eclipse/sprotty/layout/test/ElkLayoutEngineTest.xtend
There were a lot of deprecation warnings in `ElkLayoutEngineTest`, this fixes those.
=> Cleanup deprecation warnings in layout engine tests

org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/DefaultDiagramServer.java, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/SModelIndex.java, org.eclipse.sprotty/src/test/java/org/eclipse/sprotty/DefaultDiagramServerTest.xtend
=> Make selection state more consistent

org.eclipse.sprotty.layout/src/test/java/org/eclipse/sprotty/layout/test/AbstractElkTest.xtend, org.eclipse.sprotty/src/test/java/org/eclipse/sprotty/DefaultDiagramServerTest.xtend
Signed-off-by: AresEkb <denis.nikif@gmail.com>
=> Fixed line endings in tests for Windows

org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/Actions.xtend, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/DefaultDiagramServer.java
Signed-off-by: Soeren Domroes <sdo@informatik.uni-kiel.de>
=> Fixes #69 Added cause to UpdateModelAction.

org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/DiagramHighlightService.xtend, org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/DiagramSelectionListener.xtend, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/Actions.xtend
=> [selection] avoid selection cycles

org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/LanguageAwareDiagramServer.xtend, org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/ls/DiagramUpdater.xtend, org.eclipse.sprotty/src/main/java/org/eclipse/sprotty/DefaultDiagramServer.java
* Send a proper response to RequestModelAction
* Update diagram with new options if another RequestModelAction is received
=> Support requests in Xtext diagram server

Jenkinsfile, build.gradle, gradle/versions.gradle, gradle/wrapper/gradle-wrapper.properties
Update to Xtext 2.26, lsp4j 0.12.0, guice 5.0.1, gson 2.8.6 
Use Java 11 as Xtext 2.26 only runs on Java 11
=> Dependencies update
